config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy], shallow: true do
    member do
      put "like", to: "microposts#upvote"
      put "dislike", to: "microposts#downvote"
    end
    resources :comments, only: [:create, :destroy], shallow: true do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
      resources :subcomments, only: [:create, :destroy] do
        member do
          put "like", to: "subcomments#upvote"
          put "dislike", to: "subcomments#downvote"
        end
      end
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  has_many :comments, :dependent => :destroy
  acts_as_votable
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :logged_in_user, only: [:create, :destroy, :show]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      respond_to do |format|
        format.html do
          redirect_to :back
        end
        format.js do
        end
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

  def upvote
    @Micropost = Micropost.find(params[:id])
    if current_user.voted_up_on? @Micropost
      @Micropost.unliked_by current_user
    else
      @Micropost.upvote_by current_user
    end
    redirect_to :back
  end

  def downvote
    @Micropost = Micropost.find(params[:id])
    if current_user.voted_down_on? @Micropost
      @Micropost.undisliked_by current_user
    else
      @Micropost.downvote_by current_user
    end
    redirect_to :back
  end


  private
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment.html.erb
<div class="comment-row row">
    <ul id="comments-list" class="comments-list">
   <li>
    <div class="comment-main-level">
      <div class="comment-box">
        <div class="comment-head">
          <h6 class="comment-name by-author" ><%= link_to User.find(comment.creator_id).name, User.find(comment.creator_id) %></h6>
          <span>
            Posted <%= time_ago_in_words(comment.created_at) %> ago.
            <% if current_user? User.find(comment.creator_id) or current_user? comment.micropost.user%>
            <%= link_to "delete", comment, method: :delete, data: { confirm: "You sure?" } %>
            <% end %>
          </span>
        </div>
        <div class="comment-content">
         <%= comment.content %>
          <div>
            <%= link_to like_comment_path(comment), method: :put do %>
            <i class="fa <%= current_user.voted_up_on?(comment) ? 'fa-thumbs-up' : 'fa-thumbs-o-up' %>"></i> <%= comment.get_upvotes.size %>
            <% end %>

            <%= link_to dislike_comment_path(comment), method: :put do %>
            <i class="fa <%= current_user.voted_down_on?(comment) ? 'fa-thumbs-down' : 'fa-thumbs-o-down' %>"></i>  <%= comment.get_downvotes.size %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <ul class="comments-list reply-list reply-for-comment-<%= comment.id %>">
        <div class="subcomments_container">
          <%= render 'microposts/subcomments', subcomments: comment.subcomments %>
        </div>
        <%= render 'microposts/subcomment_form', subcomment: comment.subcomments.build %>
    </ul>
  </li>
</ul>
</div>

app/views/microposts/_comment_form.html.erb
<%= form_for comment, url: micropost_comments_path(comment.micropost.id), html: { class: "new_comment_form" }, remote: true do |f| %>
  <div class="dialogbox">
    <div class="body">
      <span class="tip tip-left"></span>
      <div class="message">
        <span>
           <%= f.hidden_field :micropost_id %>
           <%= f.text_area :content, placeholder: "Compose new comment..."%>
           <%= f.submit "Add comment", class: "btn btn-comment btn-primary" %>
        </span>
      </div>
    </div>
<% end %>

app/views/microposts/_comments.html.erb
<% comments.each do |comment| %>
  <%= render partial: 'microposts/comment', locals: {comment: comment} %>
<% end %>

app/views/microposts/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<%else%>
<div>
   No Microposts, click <%= link_to "here", users_path %> to follow Users !
</div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span>

    <%= link_to like_micropost_path(micropost), method: :put do %>
    <i class="fa <%= current_user.voted_up_on?(micropost) ? 'fa-thumbs-up' : 'fa-thumbs-o-up' %>"></i> <%= micropost.get_upvotes.size %>
    <% end %>

    <%= link_to dislike_micropost_path(micropost), method: :put do %>
    <i class="fa <%= current_user.voted_down_on?(micropost) ? 'fa-thumbs-down' : 'fa-thumbs-o-down' %>"></i> <%= micropost.get_downvotes.size %>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  <div class="comment_section comment-for-micropost-<%= micropost.id %>">
    <div class="comments_container">
      <%= render 'microposts/comments', comments: @post_comments_hash[micropost.id] %>
    </div>
    <%= render 'microposts/comment_form', comment: micropost.comments.build %>
  </div>
</li>

app/views/microposts/_subcomment.html.erb
<li>
<div class="comment-avatar"><%= link_to gravatar_for(User.find(subcomment.creator_id)), User.find(subcomment.creator_id)%></div>
<div class="comment-box">
  <div class="comment-head">
    <h6 class="comment-name"><%= link_to User.find(subcomment.creator_id).name, User.find(subcomment.creator_id) %></h6>
    <span>
      Posted <%= time_ago_in_words(subcomment.created_at) %> ago.
      <% if current_user? User.find(subcomment.creator_id) or current_user?subcomment.comment.micropost.user%>
      <%= link_to "delete", subcomment, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </span>
  </div>
  <div class="comment-content">
    <%= subcomment.content %>
    <span>
      <%= link_to like_subcomment_path(subcomment), method: :put do %>
      <i class="fa <%= current_user.voted_up_on?(subcomment) ? 'fa-thumbs-up' : 'fa-thumbs-o-up' %>"></i> <%= subcomment.get_upvotes.size %>
      <% end %>

      <%= link_to dislike_subcomment_path(subcomment), method: :put do %>
      <i class="fa <%= current_user.voted_down_on?(subcomment) ? 'fa-thumbs-down' : 'fa-thumbs-o-down' %>"></i> <%= subcomment.get_downvotes.size %>
      <% end %>
    </span>
  </div>
</div>
</li>

app/views/microposts/_subcomment_form.html.erb
<%= form_for subcomment, url: comment_subcomments_path(subcomment.comment.id), html: { class: "new_subcomment_form" }, remote: true do |f| %>
  <div class="container">
  <div class="dialogbox">
    <div class="reply-body">
      <span class="tip tip-up"></span>
      <div class="message">
        <span>
            <%= f.hidden_field :comment_id %>
            <%= f.hidden_field :creator_id %>
           <%= f.text_area :content, placeholder: "Compose new reply..." %>
           <%= f.submit "Reply", class: "btn btn-reply btn-primary"%>
        </span>
      </div>
    </div>
  </div>
<% end %>

app/views/microposts/_subcomments.html.erb
<% subcomments.each do |subcomment| %>
  <%= render partial: 'microposts/subcomment', locals: { subcomment: subcomment } %>
<% end %>